### ISSUE TITLE
выделить общую логику аутентификации 

### ISSUE THREAD

**Issue by foofaev** [gorushkin/backend-project-lvl4#13]
https://github.com/gorushkin/backend-project-lvl4/blob/4ca1d595024b4c5d4e619e44194f2e0b69a6b1ce/server/routes/users.js#L67

вот такие вещи должны уйти в хук
на пути это будет выглядеть, например, так: `app.auth([app.authenticate, app.checkProfileOwnership])`
(название я придумал не очень, нужно что-то получше)

**Comment by foofaev** [comment]
еще нужно добавить эти проверки в других местах
например, сейчас тут можно кому угодно поправить юзера

https://github.com/gorushkin/backend-project-lvl4/blob/4ca1d595024b4c5d4e619e44194f2e0b69a6b1ce/server/routes/users.js#L51

и стоит добавить тестов. Тест на редирект 302 - плохой, потому что всегда редиректит после выполнения пути. 
на попытку изменения чужих данных должна возвращаться ошибка доступа
они уже есть в приложении:
https://github.com/fastify/fastify-sensible
то есть можно сделать reply.methodNotAllowed()

**Comment by gorushkin** [comment]
Я вообще не понимаю как этот fastify-auth работает. Половину выходных с ним протупил. `app.auth([app.authenticate, app.checkProfileOwnership]) `это я уже пробовал, но все время получаю сообщение, что` app.auth() is not a function.`
Чертов синтаксис!!!

**Comment by gorushkin** [comment]
единственное, что смог придумать,
```
  app.decorate('tempFuncName', (request, reply, done) => {
    if (request.user.id === parseInt(request.params.id, 10)) {
      return done();
    }
    request.flash('error', i18next.t('flash.users.authError'));
    reply.redirect('/users');
    return reply;
  })
```
могу эту фигню засунуть вместо проверки аутентификации, но это не выход. Надо и то, и другое проверять.

**Comment by foofaev** [comment]
а ты его зарегистрировал в плагинах в индексе? покажи код

**Comment by gorushkin** [comment]
> а ты его зарегистрировал в плагинах в индексе? покажи код
```
const registerPlugins = (app) => {
  ... // остальыне плагины
  app.register(fastifyAuth); - // вот так вот. Или как-то еще надо? 
  ... // остальыне плагины
 }; 
```

**Comment by foofaev** [comment]
https://github.com/fastify/fastify/issues/481

вот тут объяснение, что происходит
в примерах это тоже есть
возможный обход
app.after(() => addRoutes(app))
