### ISSUE TITLE
Добавить метки

### ISSUE THREAD

**Issue by foofaev** [gorushkin/backend-project-lvl4#7]
Нужно добавить возможность создавать метки для задач.
Нужно добавить возможность добавлять метки к задачам

**Comment by gorushkin** [comment]
Черт!!! Ну и намучился я из-за своей невнимательности - два дня не мог понять почему операции в транзакциях не завершаются нормально. Только потом, в сотый раз перечитав доки, обнаружил, что надо во всех запросах передавать переменную 'trx'. А сначала тут был другой коммент, с просьбой о помощи)
Может и криво сделал все, но оно как-то работает)
